import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
export const sb=createClient('https://pcwzqwicscoelycaieka.supabase.co','sb_publishable_05iO7pksLrbFRxPnCVI11w_eqKnFgAh');
export const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export const money=n=>'R'+Number(n||0).toLocaleString('en-ZA',{maximumFractionDigits:0}).replace(/,/g,' '),today=()=>new Date().toISOString().slice(0,10),date=d=>d?new Date(String(d).length===10?d+'T12:00:00':d).toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'}):'—',addM=(d,n)=>{let x=new Date((d||today())+'T12:00:00');x.setMonth(x.getMonth()+n);return x.toISOString().slice(0,10)},addD=(d,n)=>{let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
export const svc=v=>({contest_prep:'Contest prep',lifestyle:'Lifestyle',other:'Other','Contest prep':'Contest prep','Lifestyle':'Lifestyle','Other':'Other'}[v]||v||'—'),cap=v=>String(v||'—').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export const S={profile:null,clients:[],billing:[],payments:[],tasks:[],calendar:[],content:[],research:[],coaches:[],coachEarnings:[]};
export const owner=()=>['owner','admin'].includes(S.profile?.role),hist={1:24000,2:22000,3:23000,4:25000,5:24000,6:32200,7:37000,8:13000};
export const paid=()=>S.payments.filter(p=>p.status==='paid'&&p.received_date),cashM=(y,m)=>{if(y===2026&&m<=7)return hist[m];let actual=paid().filter(p=>{let d=new Date(p.received_date+'T12:00:00');return d.getFullYear()===y&&d.getMonth()+1===m&&!(y===2026&&m===8&&p.received_date<'2026-08-11')}).reduce((a,p)=>a+Number(p.amount||0),0);return y===2026&&m===8?13000+actual:actual},cashY=y=>Array.from({length:12},(_,i)=>cashM(y,i+1)).reduce((a,b)=>a+b,0),mrr=()=>S.billing.filter(b=>b.active).reduce((a,b)=>a+Number(b.monthly_equivalent||0),0),bill=id=>S.billing.find(b=>b.client_id===id&&b.active)||S.billing.find(b=>b.client_id===id),client=id=>S.clients.find(c=>c.id===id);
export function toast(m,e=false){let t=$('#toast');t.textContent=m;t.className='toast'+(e?' error':'');setTimeout(()=>t.classList.add('hidden'),3000)}
export function pill(t,c=''){return`<span class="pill ${c}">${esc(t)}</span>`}
export function due(b){if(!b?.payment_due_date)return['—',''];let t=today(),w=addD(t,7);if(b.payment_due_date<t)return['Overdue','over'];if(b.payment_due_date<=w)return['Due soon','due'];return['Up to date','ok']}
export async function load(){let q=[['clients','name'],['client_billing','created_at'],['payments','received_date'],['tasks','due_date'],['calendar_items','start_at'],['content_items','created_at'],['research_items','published_date']];if(owner())q.push(['coaches','display_name'],['coach_earnings','period_start']);let r=await Promise.all(q.map(([t,o])=>sb.from(t).select('*').order(o,{ascending:true})));q.forEach(([t],i)=>S[{client_billing:'billing',calendar_items:'calendar',content_items:'content',research_items:'research',coach_earnings:'coachEarnings'}[t]||t]=r[i].data||[])}