import{$,esc,money,date,svc,cap,S,owner,cashM,cashY,mrr,bill,client,pill,due,today}from'./pp-lib.js';let page='home';
const navs=[['home','Dashboard'],['clients','Clients'],['payments','Payments','money'],['earnings','Earnings','money'],['planner','Calendar & Tasks'],['content','Content Planner'],['research','Research'],['coaches','Coaches','money']];
const title=(h,p,a='')=>`<div class="title"><div><h1>${h}</h1><p>${p}</p></div><div>${a}</div></div>`;
export function setPage(p){page=p}export function renderNav(){let a=navs.filter(x=>owner()||!x[2]),h=a.map(x=>`<button data-page="${x[0]}" class="${page===x[0]?'on':''}">${x[1]}</button>`).join('');$('#nav').innerHTML=h;$('#mobile').innerHTML=h}
function home(){let y=new Date().getFullYear(),m=new Date().getMonth()+1,up=S.calendar.filter(x=>String(x.start_at).slice(0,10)>=today()).slice(0,6);return title('Dashboard','The business at a glance.','<button class="btn primary" data-add="client">+ Add client</button> <button class="btn" data-add="event">+ Event</button>')+`<div class="grid four"><div class="card"><div class="label">Active clients</div><div class="value">${S.clients.filter(c=>c.status==='active').length}</div></div>${owner()?`<div class="card"><div class="label">Revenue this month</div><div class="value gold">${money(cashM(y,m))}</div></div><div class="card"><div class="label">Revenue this year</div><div class="value green">${money(cashY(y))}</div></div>`:''}<div class="card"><div class="label">Open tasks</div><div class="value">${S.tasks.filter(t=>!['done','cancelled'].includes(t.status)).length}</div></div></div><div class="section"><div class="sectionhead"><h2>Upcoming</h2></div><div class="list">${up.map(x=>`<div class="item" style="border-left:3px solid ${x.item_type==='show'?'var(--red)':'var(--gold)'}"><div><div class="name">${esc(x.title)}</div><small>${date(x.start_at)} · ${cap(x.item_type)}${x.location?' · '+esc(x.location):''}</small></div></div>`).join('')||'<div class="empty">Nothing scheduled.</div>'}</div></div>`}
export function clientRows(a=S.clients){return a.map(c=>{let b=bill(c.id),d=due(b);return`<tr data-edit="${c.id}"><td><div class="name">${esc(c.name)}</div><div class="sub">${cap(c.status)}</div></td><td>${esc(svc(c.service_type))}</td><td>${money(b?.monthly_equivalent)}</td><td>${pill(b?.billing_type==='lump_sum'?'Lump sum':b?.billing_type==='free'?'Free':'Monthly',b?.billing_type==='lump_sum'?'lump':'')}</td><td>${esc(b?.payment_method||'—')}</td><td>${date(b?.payment_due_date)} ${b?.billing_type==='free'?'':pill(d[0],d[1])}</td></tr>`}).join('')}
function clients(){return title('Clients','Roster and billing.','<button class="btn primary" data-add="client">+ Add client</button>')+`<div class="toolbar"><input id="search" class="input" placeholder="Search clients"></div><div class="tablewrap"><table><thead><tr><th>Client</th><th>Service</th><th>Monthly equiv.</th><th>Billing</th><th>Method</th><th>Next due</th></tr></thead><tbody id="rows">${clientRows()}</tbody></table></div>`}
function payments(){let rows=S.billing.filter(b=>b.active&&b.billing_type!=='free').map(b=>{let c=client(b.client_id),d=due(b),amt=b.billing_type==='lump_sum'?b.lump_sum_amount:b.monthly_equivalent;return`<tr><td>${esc(c?.name)}</td><td>${money(amt)}</td><td>${cap(b.billing_type)}</td><td>${esc(b.payment_method)}</td><td>${date(b.payment_due_date)} ${pill(d[0],d[1])}</td><td><button class="btn sm primary" data-paid="${b.id}">Mark paid</button></td></tr>`}).join('');return title('Payments','Monthly and lump-sum payments.')+`<div class="tablewrap"><table><thead><tr><th>Client</th><th>Cash due</th><th>Type</th><th>Method</th><th>Due</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function earnings(){return title('Earnings','Historical figures preserved; new payments add automatically.')+`<div class="grid four"><div class="card"><div class="label">Revenue this year</div><div class="value gold">${money(cashY(2026))}</div></div><div class="card"><div class="label">Revenue this month</div><div class="value gold">${money(cashM(2026,8))}</div></div><div class="card"><div class="label">Monthly equivalent</div><div class="value green">${money(mrr())}</div></div><div class="card"><div class="label">Active clients</div><div class="value">${S.clients.filter(c=>c.status==='active').length}</div></div></div><div class="note section">Jan–Jul remain as before. August begins at R13 000 for 1–10 Aug, then adds recorded payments from 11 Aug onward. Lump sums count in full.</div><div class="tablewrap section"><table><thead><tr><th>Month</th><th>Revenue</th></tr></thead><tbody>${Array.from({length:12},(_,i)=>`<tr><td>${new Date(2026,i).toLocaleString('en',{month:'long'})}</td><td><b>${money(cashM(2026,i+1))}</b></td></tr>`).join('')}</tbody></table></div>`}
function planner(){return title('Calendar & Tasks','Shows, travel, business and personal planning.','<button class="btn primary" data-add="event">+ Event</button> <button class="btn" data-add="task">+ Task</button>')+`<div class="grid two"><div><div class="sectionhead"><h2>Agenda</h2></div><div class="list">${S.calendar.map(x=>`<div class="item"><div><div class="name">${esc(x.title)}</div><small>${date(x.start_at)} · ${cap(x.item_type)}</small></div></div>`).join('')||'<div class="empty">Nothing scheduled.</div>'}</div></div><div><div class="sectionhead"><h2>Tasks</h2></div><div class="list">${S.tasks.map(x=>`<div class="item"><div><div class="name">${esc(x.title)}</div><small>${date(x.due_date)} · ${cap(x.priority)}</small></div><button class="btn sm" data-done="${x.id}">Done</button></div>`).join('')||'<div class="empty">No tasks.</div>'}</div></div></div>`}
function content(){return title('Content Planner','Saved content ideas.')+`<div class="list">${S.content.map(x=>`<div class="item"><div><div class="name">${esc(x.title)}</div><small>${cap(x.content_type)} · ${cap(x.status)}</small></div></div>`).join('')||'<div class="empty">No content ideas yet.</div>'}</div>`}
function research(){return title('Research','Curated bodybuilding and fitness studies.')+`<div class="list">${S.research.map(x=>`<div class="item"><div><div class="name">${esc(x.title)}</div><small>${esc(x.source||'')} · ${date(x.published_date)}</small></div></div>`).join('')||'<div class="empty">No research saved yet.</div>'}</div>`}
function coaches(){return title('Coaches','Owner-only coach overview.')+`<div class="tablewrap"><table><thead><tr><th>Coach</th><th>Commission</th><th>Clients</th></tr></thead><tbody>${S.coaches.map(c=>`<tr><td>${esc(c.display_name)}</td><td>${cap(c.commission_type)}</td><td>${S.clients.filter(x=>x.assigned_coach_id===c.id).length}</td></tr>`).join('')}</tbody></table></div>`}
export function render(){let f={home,clients,payments,earnings,planner,content,research,coaches}[page];$('#main').innerHTML=f()}